### PR TITLE
Extend Lukkit documentation with GUI

### PR DESCRIPTION
**Pull request by fHpro0**

### CODE REVIEW

**Comment by AL1L** [comment]
Maybe some screenshots or gifs of the inventory it creates?

**Comment by fHpro0** [comment]
> screenshots
Better? 😂 
b4ef0a2
5daaee9

**Review by AL1L — APPROVED** [review]
I like

**Review by mathhulk — APPROVED** [review]
Great additions!

**Comment by AL1L** [comment]
Changes are live @fHpro0 🎉

**Pull request merged**
